export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const TASK_UPDATE = 'TASK_UPDATE';
export const TASK_CREATE = 'TASK_CREATE';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_SAVE = 'TASK_SAVE';
export const TASK_SAVE_SUCCESS = 'TASK_SAVE_SUCCESS';
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS';
export const TASK_SELECTED = 'TASK_SELECTED';