export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const TASK_UPDATE = 'TASK_UPDATE';
export const TASK_CREATE = 'TASK_CREATE';
export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_SAVE = 'TASK_SAVE';
export const TASK_SAVE_SUCCESS = 'TASK_SAVE_SUCCESS';
export const TASKS_FETCH_SUCCESS = 'TASKS_FETCH_SUCCESS';
export const TASK_SELECTED = 'TASK_SELECTED';
export const LOCATION_CHANGED = 'LOCATION_CHANGED';

export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const QUANTITY_CHANGED = 'QUANTITY_CHANGED';
export const TEXT_CHANGED = 'TEXT_CHANGED';
export const PRODUCTS_FETCH_START = 'PRODUCTS_FETCH_START';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_FAIL = 'PRODUCTS_FETCH_FAIL';
export const REPORT_CREATE_START = 'REPORT_CREATE_START';
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL';
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS';
export const REPORT_FETCH_START = 'REPORT_FETCH_START';
export const REPORT_FETCH_FAIL = 'REPORT_FETCH_FAIL';
export const REPORT_FETCH_SUCCESS = 'REPORT_FETCH_SUCCESS';