export const LOCATION_CHANGED = 'LOCATION_CHANGED';
export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const QUANTITY_CHANGED = 'QUANTITY_CHANGED';
export const TEXT_CHANGED = 'TEXT_CHANGED';

export const PRODUCTS_FETCH_START = 'PRODUCTS_FETCH_START';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_FAIL = 'PRODUCTS_FETCH_FAIL';

export const REPORT_CREATE_START = 'REPORT_CREATE_START';
export const REPORT_CREATE_FAIL = 'REPORT_CREATE_FAIL';
export const REPORT_CREATE_SUCCESS = 'REPORT_CREATE_SUCCESS';

export const REPORT_FETCH_START = 'REPORT_FETCH_START';
export const REPORT_FETCH_FAIL = 'REPORT_FETCH_FAIL';
export const REPORT_FETCH_SUCCESS = 'REPORT_FETCH_SUCCESS';